user_token: YTkyMmNiNTktN2ZjNS00ZTRmLWI2MTMtOGRhOGNiMTU4ODVkXzEyNjM=

session:
  key: m5hidm8ukhfpydkokdf25hyz652jlmci
admin:
  email: admin@admin.com
  password: admin
bot:
  token: group_token
  group_id: 1


